import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, FileCheck2, FileText, ShieldCheck, Sparkles } from "lucide-react";
import markAsset from "@/assets/coredoc-logo.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "CoreDoc — Free Invoice & Quotation Generator" }, { name: "description", content: "Create polished invoices and quotations in minutes. Free, private, and no login required." }, { property: "og:title", content: "CoreDoc — Free Invoice & Quotation Generator" }, { property: "og:description", content: "Create polished business documents in minutes. No login required." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Home,
});

function Home() {
  const benefits = ["No login required", "Free to use", "Private by design", "PDF ready", "Easy to share", "Works on mobile"];
  return <main className="min-h-screen bg-background">
    <nav className="border-b border-border"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link to="/" className="flex items-center gap-2.5"><img src={markAsset.url} alt="" className="h-9 w-9 object-contain" /><span className="text-lg font-bold text-foreground">CoreDoc</span></Link><span className="rounded-full bg-accent px-3 py-1 text-xs font-bold text-accent-foreground">Free forever</span></div></nav>
    <section className="mx-auto grid min-h-[600px] max-w-6xl items-center gap-10 px-5 py-16 lg:grid-cols-[1.1fr_0.9fr] lg:py-20">
      <div><div className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-primary"><Sparkles className="h-4 w-4" />Simple documents. Professional results.</div><h1 className="max-w-3xl text-4xl font-bold leading-tight text-foreground sm:text-5xl lg:text-6xl">Create professional invoices & quotations.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Build a polished business document in minutes. No login, no signup, and no complicated setup.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/invoice" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-primary px-6 text-sm font-bold text-primary-foreground transition hover:bg-primary/90">Create invoice <ArrowRight className="h-4 w-4" /></Link><Link to="/quotation" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-border bg-card px-6 text-sm font-bold text-foreground transition hover:bg-accent">Create quotation <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-9 grid max-w-xl grid-cols-2 gap-x-4 gap-y-3 sm:grid-cols-3">{benefits.map((benefit) => <div key={benefit} className="flex items-center gap-2 text-sm text-muted-foreground"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-success-soft text-success"><Check className="h-3.5 w-3.5" /></span>{benefit}</div>)}</div></div>
       <div className="relative mx-auto w-full max-w-md"><div className="absolute inset-x-8 bottom-0 h-24 bg-primary/10 blur-3xl" /><div className="relative border border-border bg-card p-7 shadow-showcase"><div className="flex items-center justify-between border-b border-border pb-5"><div className="flex items-center gap-3"><img src={markAsset.url} alt="CoreDoc document mark" className="h-14 w-14 object-contain" /><div><p className="font-bold">CoreDoc</p><p className="text-xs text-muted-foreground">Business documents</p></div></div><FileCheck2 className="h-7 w-7 text-primary" /></div><div className="space-y-4 py-6"><div className="h-2 w-1/3 rounded-full bg-primary/20" /><div className="h-3 w-3/4 rounded-full bg-muted" /><div className="grid grid-cols-3 gap-2"><div className="h-16 rounded-md bg-accent" /><div className="h-16 rounded-md bg-accent" /><div className="h-16 rounded-md bg-primary" /></div><div className="h-2 w-full rounded-full bg-muted" /><div className="h-2 w-4/5 rounded-full bg-muted" /></div><div className="flex items-center justify-between border-t border-border pt-5"><span className="text-xs font-semibold text-muted-foreground">TOTAL</span><span className="text-xl font-bold text-primary">₹17,700</span></div></div></div>
    </section>
    <section className="border-y border-border bg-soft"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-12 md:grid-cols-3">{[{ icon: FileText, title: "Create", text: "Enter the details that matter, without accounting software complexity." }, { icon: FileCheck2, title: "Preview", text: "See a clean A4 document update instantly as you type." }, { icon: ShieldCheck, title: "Download & share", text: "Export a document-only PDF. Your information stays on your device." }].map(({ icon: Icon, title, text }, index) => <div key={title} className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-primary text-primary-foreground">{index + 1}</span><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></section>
    <footer className="mx-auto flex max-w-6xl flex-col gap-2 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="font-semibold text-foreground">CoreDoc</span><span>Created by <span aria-label="love" role="img">❤️</span> CorePro Techno LLP</span></footer>
  </main>;
}
